#!/bin/bash

mkdir logs
echo "TjSDBkAu"
ssh-copy-id -o StrictHostKeyChecking=no root@10.1.1.10
latestfiles=`ssh -o StrictHostKeyChecking=no root@10.1.1.10 find /log/dataflash -mtime -1 -type f`
for i in $latestfiles
do
	scp -o StrictHostKeyChecking=no -o UserKnownHostsFile='/dev/null' root@10.1.1.10:$i ./logs
done
# pwd TjSDBkAu
